/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tisaj.obracunplace.view;

import java.awt.Toolkit;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import tisaj.obracunplace.controller.ObradaIsplata;
import tisaj.obracunplace.controller.ObradaObracun;
import tisaj.obracunplace.controller.ObradaRadnik;
import tisaj.obracunplace.controller.ObradaVrstaPrimanja;
import tisaj.obracunplace.model.Isplata;
import tisaj.obracunplace.model.Obracun;
import tisaj.obracunplace.model.Radnik;
import tisaj.obracunplace.model.VrstaPrimanja;
import tisaj.obracunplace.pomocno.ObracunPlaceException;

/**
 *
 * @author Josip
 */
public class Obracuni extends javax.swing.JFrame {

    private final ObradaObracun obradaObracun;
    private final ObradaRadnik obradaRadnik;
    private final ObradaIsplata obradaIsplata;
    private static DefaultComboBoxModel<Radnik> modelRadnik;
    private static DefaultComboBoxModel<Isplata> modelIsplata;
    private static DefaultComboBoxModel<VrstaPrimanja> modelVrstaPrimanja;
    private static DefaultComboBoxModel<Obracun> modelObracun;
    private Obracun obracun;
    private Isplate isplate;

    /**
     * Creates new form Obracuni
     */
    public Obracuni() {
        initComponents();
        obradaObracun = new ObradaObracun();
        obradaRadnik = new ObradaRadnik();
        obradaIsplata = new ObradaIsplata();

        DefaultComboBoxModel<VrstaPrimanja> ms = new DefaultComboBoxModel<>();
        VrstaPrimanja vp = new VrstaPrimanja();
        vp.setId(0);
        vp.setNazivVrstePrimanja("Odaberite vrstu primanja");
        ms.addElement(vp);
        new ObradaVrstaPrimanja().getLista().forEach((s) -> {
            ms.addElement(s);
        });
        cmbVrstaPrimanja.setModel(ms);

        DefaultComboBoxModel<Isplata> i = new DefaultComboBoxModel<>();
        Isplata ii = new Isplata();
        ii.setId(0);
        ii.setNazivIsplate("Odaberite naziv isplate");
        i.addElement(ii);
        new ObradaIsplata().getLista().forEach((is) -> {
            i.addElement(is);
        });
        cmbIsplata.setModel(i);

        DefaultComboBoxModel<Radnik> r = new DefaultComboBoxModel<>();
        Radnik rr = new Radnik();
        

//        DefaultComboBoxModel<Obracun> o = new DefaultComboBoxModel<>();
//        Obracun oo = new Obracun();
//        new ObradaObracun().getLista().forEach((ooo) -> {
//            o.addElement(ooo);
//        });
//        cmbObracuni.setModel(o);

        ucitajPodatke();

        seticon();
    }

    private void ucitajPodatke() {
        DefaultListModel<Obracun> ob = new DefaultListModel<>();
        obradaObracun.getLista().forEach((o) -> {
            ob.addElement(o);
        });
        lstObracun.setModel(ob);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        lstRadniciNaObracunu = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstObracun = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstRadnici = new javax.swing.JList<>();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();
        txtUvjet = new javax.swing.JTextField();
        chbLimitator = new javax.swing.JCheckBox();
        cmbVrstaPrimanja = new javax.swing.JComboBox<>();
        btnOčisti = new javax.swing.JButton();
        txtKolicina = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnMakniSObracuna = new javax.swing.JButton();
        btnDodajNaObracun = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnIzracun = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbIsplata = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Obračuni");

        lstRadniciNaObracunu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lstRadniciNaObracunu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRadniciNaObracunuValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstRadniciNaObracunu);

        lstObracun.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstObracunValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstObracun);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Vrsta Primanja");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Količina sati");

        lstRadnici.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRadniciValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstRadnici);

        btnDodaj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDodaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tisaj/obracunplace/pomocno/Button-Add-icon (1).png"))); // NOI18N
        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnObrisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tisaj/obracunplace/pomocno/Button-Delete-icon.png"))); // NOI18N
        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnPromjeni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPromjeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tisaj/obracunplace/pomocno/Button-Refresh-icon.png"))); // NOI18N
        btnPromjeni.setText("Promjeni");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        txtUvjet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUvjetKeyReleased(evt);
            }
        });

        chbLimitator.setSelected(true);
        chbLimitator.setText("Limitiraj na 25");

        btnOčisti.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOčisti.setText("Očisti");
        btnOčisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOčistiActionPerformed(evt);
            }
        });

        txtKolicina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtKolicina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKolicina.setText("0.0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Radnici u bazi");

        btnMakniSObracuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tisaj/obracunplace/pomocno/right.png"))); // NOI18N
        btnMakniSObracuna.setToolTipText("");
        btnMakniSObracuna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btnMakniSObracuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakniSObracunaActionPerformed(evt);
            }
        });

        btnDodajNaObracun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tisaj/obracunplace/pomocno/left.png"))); // NOI18N
        btnDodajNaObracun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        btnDodajNaObracun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNaObracunActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Radnici na obracunu");

        btnIzracun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIzracun.setText("Izračun");
        btnIzracun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzracunActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Isplata");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPromjeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOčisti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addComponent(btnDodaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbVrstaPrimanja, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbIsplata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnIzracun, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDodajNaObracun, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMakniSObracuna, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(chbLimitator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chbLimitator)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(btnDodajNaObracun, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnMakniSObracuna, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(263, 263, 263)
                                        .addComponent(btnDodaj)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPromjeni)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnObrisi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnOčisti, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnIzracun, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbIsplata, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cmbVrstaPrimanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        Obracun o = new Obracun();
        

        o.setIsplata((Isplata) cmbIsplata.getSelectedItem());
        o.setVrstaPrimanja((VrstaPrimanja) cmbVrstaPrimanja.getSelectedItem());
        o.setKolicinaSati(Double.parseDouble(txtKolicina.getText()));
        try {
            obradaObracun.save(o);
            ocistiPolja();
            ucitajPodatke();
        } catch (ObracunPlaceException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        Obracun obra = lstRadniciNaObracunu.getSelectedValue();

        if (obra == null) {
            JOptionPane.showConfirmDialog(null, "Prvo odaberite obračun");
        }
        try {
            obradaObracun.delete(obra);
            ucitajPodatke();
            ocistiPolja();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Obračun nije obrisan");
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        obracun = lstRadniciNaObracunu.getSelectedValue();
        if (obracun == null) {
            JOptionPane.showMessageDialog(null, "Prvo odaberite obracun");
            return;
        }
        obracun = preuzmiVrijednosti(obracun);
        spremi(obracun);
    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void lstObracunValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstObracunValueChanged


    }//GEN-LAST:event_lstObracunValueChanged

    private void lstRadniciValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRadniciValueChanged
        
    }//GEN-LAST:event_lstRadniciValueChanged

    private void btnOčistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOčistiActionPerformed
        ocistiPolja();
    }//GEN-LAST:event_btnOčistiActionPerformed

    private void txtUvjetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUvjetKeyReleased
        ucitajEntitete();
    }//GEN-LAST:event_txtUvjetKeyReleased

    private void btnMakniSObracunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakniSObracunaActionPerformed
        if (obracun == null) {
            JOptionPane.showMessageDialog(null, "Prvo odaberite obracun");
            return;
        }
        
        List<Integer> zaBrisanje = new ArrayList<>();
        lstRadniciNaObracunu.getSelectedValuesList().forEach((p)->{zaBrisanje.add(p.getId());});
        
        
        for(int i=0;i<obracun.get().size();i++){                    // TO DO
            for(int b : zaBrisanje){
                if(obracun.get().get(i).getSifra()==b){                 // TO DO
                   obracun.get().remove(i);                             // TO DO
                   break;
                }
            }
        }
        
        ucitajRadnike(obracun);
    }//GEN-LAST:event_btnMakniSObracunaActionPerformed

    private void lstRadniciNaObracunuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRadniciNaObracunuValueChanged

    }//GEN-LAST:event_lstRadniciNaObracunuValueChanged

    private void btnDodajNaObracunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNaObracunActionPerformed
        if (obracun == null) {
            JOptionPane.showMessageDialog(null, "Prvo odaberite obracun");
            return;
        }

        lstRadnici.getSelectedValuesList().forEach((p) -> {

            boolean postoji = false;
            for (int i = 0; i < lstRadniciNaObracunu.getModel().getSize(); i++) {
                if (p.getId() == lstRadniciNaObracunu.getModel().getElementAt(i).getId()) {
                    postoji = true;
                    break;
                }
            }
            if (!postoji) {
               obracun.getRadnik().add(p);                                          //TO DO
                //p.getGrupe().add(grupa);
            }

        });

        ucitajRadnike(obracun);

    }//GEN-LAST:event_btnDodajNaObracunActionPerformed

    private void btnIzracunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzracunActionPerformed
        
    }//GEN-LAST:event_btnIzracunActionPerformed

    private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("obracun.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajNaObracun;
    private javax.swing.JButton btnIzracun;
    private javax.swing.JButton btnMakniSObracuna;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOčisti;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JCheckBox chbLimitator;
    private javax.swing.JComboBox<Isplata> cmbIsplata;
    private javax.swing.JComboBox<VrstaPrimanja> cmbVrstaPrimanja;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<Obracun> lstObracun;
    private javax.swing.JList<Radnik> lstRadnici;
    private javax.swing.JList<Obracun> lstRadniciNaObracunu;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtUvjet;
    // End of variables declaration//GEN-END:variables

    private void ocistiPolja() {
        
        cmbIsplata.setSelectedIndex(0);
        cmbVrstaPrimanja.setSelectedIndex(0);
        txtKolicina.setText("0.0");
    }

    private Obracun preuzmiVrijednosti(Obracun o) {
        
        o.setIsplata((Isplata) cmbIsplata.getSelectedItem());
        o.setVrstaPrimanja((VrstaPrimanja) cmbVrstaPrimanja.getSelectedItem());
        o.setKolicinaSati(Double.parseDouble(txtKolicina.getText()));

        return o;
    }

    private void ucitajEntitete() {
        if (chbLimitator.isSelected()) {
            DefaultListModel<Radnik> m = new DefaultListModel<>();
            for (Radnik s : obradaRadnik.getLista(txtUvjet.getText().trim(), chbLimitator.isSelected())) {
                m.addElement(s);
            }
            lstRadnici.setModel(m);
        } else {
            DefaultListModel<Radnik> r = new DefaultListModel<>();
            Radnik rr = new Radnik();
            rr.setIme("Molim");
            rr.setPrezime("pričekati");
            r.addElement(rr);
            lstRadnici.setModel(r);
            DuzeUcitanjeEntiteta d = new DuzeUcitanjeEntiteta();
            d.start();
        }

    }

    private String getObracun() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private class DuzeUcitanjeEntiteta extends Thread {

        @Override
        public void run() {
            DefaultListModel<Radnik> m = new DefaultListModel<>();
            for (Radnik s : obradaRadnik.getLista(txtUvjet.getText().trim(), chbLimitator.isSelected())) {
                m.addElement(s);
            }
            lstRadnici.setModel(m);
        }

    }

    private void ucitajRadnike(Obracun o) {

        DefaultListModel<Radnik> r = new DefaultListModel<>();

        o.().forEach((p) -> {                                  // TO DO 

            r.addElement(p);

        });
        lstRadniciNaObracunu.setModel(r);
    }

    

    private void spremi(Obracun o) {
        try {
            obradaObracun.save(o);
            ocistiPolja();
            ucitajPodatke();
        } catch (ObracunPlaceException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    
    
    

}
